BuyingMenu :
  title: "§e☆ §b§lAchat de points Farm §e☆"
  size: 27
  items :
    0:
      material: "NETHER_STAR"
      place : 11
      price: 10000000
      name: "§b§l1 Point Farm"
      lore:
        - "§aPrix : 10 000 000 ✰"
    1:
      material: "NETHER_STAR"
      place: 13
      price: 50000000
      name: "§b§l5 Points Farm"
      lore:
        - "§aPrix : 50 000 000 ✰"
    2:
      material: "NETHER_STAR"
      place: 15
      price: 150000000
      name: "§b§l15 Points Farm"
      lore:
        - "§aPrix : 150 000 000 ✰"
    3:
      material: "WOOD_DOOR"
      place: 26
      price: 0
      name: "§cRetour"
      lore:
        - " "