BuyingMenu :
  title: "§e☆ §b§lAchat de points Farm §e☆"
  size: 27
  items :
    0:
      material: "NETHER_STAR"
      place : 11
      price: 10000000
      name: "§b§l1 Point Farm"
      numberOfPoints: 1
      lore:
        - "§aPrix : 10 000 000 ✰"
    1:
      material: "NETHER_STAR"
      place: 13
      price: 50000000
      name: "§b§l5 Points Farm"
      numberOfPoints: 5
      lore:
        - "§aPrix : 50 000 000 ✰"
    2:
      material: "NETHER_STAR"
      place: 15
      price: 150000000
      name: "§b§l15 Points Farm"
      numberOfPoints: 15
      lore:
        - "§aPrix : 150 000 000 ✰"
    3:
      material: "WOOD_DOOR"
      place: 26
      price: 0
      name: "§cRetour"
      numberOfPoints: 0
      lore:
        - " "
RankingMenu :
  title: "§e☆ §b§lTop Farm §e☆"
  size: 45
  factionNamePrefix: "§d§l"
  factionPointPrefix: "  |  §b§l"
  factionPointSuffix: " points"
  topFactions:
    1:
      material: "EMERALD"
      place: 20
      lore:
        - ""
        - "§eRécompenses:"
        - "§7⦁ §f7 500 Points boutique §7(Chef)"
        - "§7⦁ §fTag §a§lFermier §7(Faction)"
    2:
      material: "EMERALD"
      place: 22
      lore:
        - ""
        - "§eRécompenses:"
        - "§7⦁ §f7 500 Points boutique §7(Chef)"
        - "§7⦁ §fTag §a§lFermier §7(Faction)"
    3:
      material: "EMERALD"
      place: 24
      lore:
        - ""
        - "§eRécompenses:"
        - "§7⦁ §f7 500 Points boutique §7(Chef)"
        - "§7⦁ §fTag §a§lFermier §7(Faction)"
Glass:
  place :
    - 0
    - 1
    - 9
    - 7
    - 8
    - 17
    - 27
    - 36
    - 37
    - 35
    - 43
    - 44
  name : "§e☆"